# Generated by Django 3.1.3 on 2021-01-14 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(verbose_name='titulo')),
                ('ubicacion', models.TextField(verbose_name='ubicacion')),
                ('precio', models.TextField(verbose_name='precio')),
                ('body', models.TextField(verbose_name='precio')),
                ('image', models.URLField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Nombre')),
                ('food', models.TextField(default='Otro', verbose_name='Tipos de Comida')),
                ('points', models.FloatField(default=0.0, verbose_name='Puntuacion')),
                ('num_reviews', models.IntegerField(default=0, verbose_name='Numero de puntuaciones')),
                ('min_price', models.IntegerField(default=0, verbose_name='Menor precio')),
                ('max_price', models.IntegerField(default=0, verbose_name='Mayor precio')),
                ('location', models.TextField(default='Desconocido', verbose_name='Ubicacion')),
                ('image', models.URLField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(verbose_name='titulo')),
                ('body', models.TextField(verbose_name='cuerpo')),
                ('point', models.FloatField(verbose_name='puntuacion')),
                ('fecha', models.DateField(verbose_name='fecha')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.restaurante')),
            ],
        ),
    ]
