# Generated by Django 3.1.3 on 2021-01-07 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210107_0144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurante',
            name='location_url',
        ),
    ]
